apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  namespace: demo
  labels:
      type: my-pvc
spec:
  # storageClassName: standard # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: my-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
    # selector:
    #   matchLabels:
    #     type: my-pv


